# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75d9f321dc64556c2d35760f46a55236040930b82c3058d75c4aa72a2b723ec212350f76343195db206fce4e11c305800e05f0e7c48576aa1aed3febffdd2ede

test:
  secret_key_base: e0e7f3ed29594867419aa145b83163d607b95bf123548a36830395bc4b87030a663d7b523e483d8d731ea80075c3ae5b59d5804b5aadd32d81ec2bad4674c4c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
